package com.softserveinc.softtour.parsers.constants;

public interface TyrComUaParserConstants {
    String RESOURCE_PATH_COUNTRY_VOCABULARY = "/parser_properties/country_ua-ru_vocabulary";
    String RESOURCE_PATH_REGION_VOCABULARY = "/parser_properties/region_ua-ru_vocabulary";
    String RESOURCE_PATH_DEPARTURE_CITY_VOCABULARY = "/parser_properties/departure-city_ua-ru_vocabulary";
    String DEFAULT_CHARSET = "UTF-8";
    String URL_TYR_COM_UA = "http://www.tyr.com.ua/tours/search.php";
    String DEFAULT_COUNTRY = "Єгипет";
    String DROP_DOWN_COUNTRY_ID = "itt_country";
    String SELECT_REGION_ID = "region_list";
    String SELECT_HOTEL_ID = "hotel_list";
    String MULTIPLY_STARS_2_XPATH = "//input[@value='7' and @name='hotel_rating_list']";
    String MULTIPLY_STARS_3_XPATH = "//input[@value='3' and @name='hotel_rating_list']";
    String MULTIPLY_STARS_4_XPATH = "//input[@value='4' and @name='hotel_rating_list']";
    String MULTIPLY_STARS_5_XPATH = "//input[@value='78' and @name='hotel_rating_list']";
    String FOOD_HB_XPATH = "HB";
    String FOOD_BB_XPATH = "BB";
    String FOOD_FB_XPATH = "FB";
    String FOOD_AI_XPATH = "AI";
    String FOOD_UAI_XPATH = "UAI";
    String FOOD_RO_XPATH = "RO";
    String MULTIPLY_FOOD_HB_XPATH = "//input[@value='496' and @name='food_list']";
    String MULTIPLY_FOOD_BB_XPATH = "//input[@value='388' and @name='food_list']";
    String MULTIPLY_FOOD_FB_XPATH = "//input[@value='498' and @name='food_list']";
    String MULTIPLY_FOOD_AI_XPATH = "//input[@value='512' and @name='food_list']";
    String MULTIPLY_FOOD_UAI_XPATH = "//input[@value='560' and @name='food_list']";
    String MULTIPLY_FOOD_RO_XPATH = "//input[@value='1956' and @name='food_list']";
    String DROP_DOWN_ADULTS_ID = "adult";
    String DROP_DOWN_CHILDREN_ID = "children";
    String SEND_CHILD_1_AGE_ID = "child1_age";
    String SEND_CHILD_2_AGE_ID = "child2_age";
    String SEND_CHILD_3_AGE_ID = "child3_age";
    String SEND_DATE_FLY_FROM_ID = "itt_date_from";
    String SEND_DATE_FLY_TO_ID = "date_till";
    String DROP_DOWN_NIGHTS_FROM_ID = "night_from";
    int DEFAULT_NIGHTS_COUNT_FROM = 6;
    String DROP_DOWN_NIGHTS_TO_ID = "night_till";
    String SEND_PRICE_FROM_ID = "price_from";
    int DEFAULT_NIGHTS_COUNT_TO = 14;
    String SEND_PRICE_TO_ID = "price_till";
    String DEFAULT_CURRENCY = "USD";
    String DEFAULT_DEPARTURE_CITY = "Київ";
    String DROP_DOWN_CURRENCY_ID = "switch_price";
    String DROP_DOWN_DEPARTURE_CITY_NAME = "departure_city";
    String RADIO_BUTTON_COUNT_PAGES_100_ID = "items_per_page100";
    String BUTTON_SUBMIT_XPATH = "//input[@value='Найти' and @type='button']";
    String PARSE_RESULTS_BY_CLASS_NAME_ODD = "itt_odd";
    String PARSE_RESULTS_BY_CLASS_NAME_EVEN = "itt_even";
    String WHILE_NEXT_BUTTON = "Следующая";
    String RESULT_LIST_LEFT_CLASS_NAME = "itt_text-left";
    String RESULT_LIST_CENTER_CLASS_NAME = "text-center";
    String RESULT_LIST_RIGHT_CLASS_NAME = "text-right";
    String NO_DEPARTURE = "Без перелета";
    String NO_DEPARTURE_UA = "Авіапереліт не входить у вартість туру";
    String SIMPLE_DATE_FORMAT_DATE = "dd.mm.yy";
    String LINK_TO_PICTURE = "//a[@class='it_small_price']";
    String GET_TOUR_TIME = "ittour_order_description";
    String NO_PICTURE = "No picture";
    String JAVASCRIPT_CODE = "return(function foo(){var bar = document.getElementById('main_img_tour_in_view_open_').getAttribute('src');return bar})()";
}
