INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (1, 'Анталія', 5200, 4);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (2, 'Шарм аль Шейх', 5996, 1);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (3, 'Афіни', 7659, 3);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (4, 'Айа напа', 6700, 5);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (5, 'Дахаб', 5486, 6);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (6, 'Макади Бей', 2, 6);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (7, 'Марса Алам', 5478, 6);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (8, 'Нувейба', 5377, 6);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (9, 'Сафага', 5409, 6);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (10, 'Сахл Хашиш', 5522, 6);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (11, 'Сома Бей', 3, 6);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (12, 'Таба', 5185, 6);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (13, 'Хургада', 1, 6);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (14, 'Шарм Эль Шейх', 5996, 6);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (15, 'Эль Гуна', 5476, 6);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (16, 'Эль Кусейр', 5509, 6);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (17, 'Аланья', 6192, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (18, 'Анкара', 19522, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (19, 'Анталия', 5200, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (20, 'Белек', 6818, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (21, 'Бодрум', 5206, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (22, 'Даламан', 5597, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (23, 'Кемер', 5186, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (24, 'Кушадасы', 5195, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (25, 'Мармарис', 6578, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (26, 'Сиде', 5202, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (27, 'Стамбул', 5498, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (28, 'Улудаг', 5210, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (29, 'Фетхие', 6576, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (30, 'Эрзурум', 6019, 7);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (31, 'Абу Даби', 7070, 8);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (32, 'Аджман', 6712, 8);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (33, 'Дубаи', 5930, 8);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (34, 'Корфаккан', 5512, 8);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (35, 'Рас Аль Хайма', 7016, 8);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (36, 'Рас Аль Хайма + Дубаи', 11446, 8);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (37, 'Умм Аль Кувейн', 6033, 8);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (38, 'Фуджейра', 7068, 8);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (39, 'Фуджейра + Дубаи', 10332, 8);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (40, 'Шарджа', 6035, 8);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (41, 'Астипалея', 43490, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (42, 'Аттика', 15226, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (43, 'Афины', 7659, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (44, 'Афон', 29510, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (45, 'Дельфы', 11402, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (46, 'Кавала', 25114, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (47, 'Калимнос', 43502, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (48, 'Карпатос', 25112, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (49, 'Кассандра', 29388, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (50, 'Кастелоризо', 43509, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (51, 'Касторья', 9544, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (52, 'Корфу', 5270, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (53, 'Кос', 5343, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (54, 'Лерос', 43498, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (55, 'Лесбос', 43499, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (56, 'Лутраки', 7661, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (57, 'Неа Калликратия', 29526, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (58, 'о. Крит', 38154, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (59, 'о. Миконос', 16678, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (60, 'о. Родос', 6742, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (61, 'о. Санторини', 7382, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (62, 'о. Эвбея', 28328, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (63, 'Патмос', 28171, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (64, 'Пелла', 9546, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (65, 'Пелопоннес', 17140, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (66, 'Пиерия', 9600, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (67, 'Салоники', 5411, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (68, 'Самос', 21240, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (69, 'Сими', 28507, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (70, 'Ситония', 29501, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (71, 'Тасос', 21220, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (72, 'Тилос', 37490, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (73, 'Халки', 43503, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (74, 'Хиос', 25108, 9);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (75, 'Бечичи', 6752, 10);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (76, 'Будва', 6984, 10);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (77, 'Петровац', 6782, 10);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (78, 'Пржно/Милочер', 27713, 10);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (79, 'Св.Стефан', 6778, 10);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (80, 'Барселона', 5277, 11);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (81, 'Гран Канария', 6130, 11);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (82, 'Ибица', 5321, 11);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (83, 'Коста Бланка', 5271, 11);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (84, 'Коста Брава', 5274, 11);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (85, 'Коста Даурада', 5404, 11);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (86, 'Коста Дель Соль', 5278, 11);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (87, 'Мадрид', 23705, 11);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (88, 'Майорка', 5250, 11);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (89, 'о. Тенерифе', 6052, 11);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (90, 'Экскурсионный тур - Испания', 6296, 11);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (91, 'Бад Гаштайн', 6726, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (92, 'Бад Кляйнкирххайм', 10966, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (93, 'Бад Хофгаштайн', 5846, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (94, 'Баден', 5234, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (95, 'Вена', 5461, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (96, 'Гальтюр', 5305, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (97, 'Заальбах', 5408, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (98, 'Зальцбург', 5412, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (99, 'Зальцбургерланд', 21757, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (100, 'Зеефельд', 5419, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (101, 'Зель Ам Вильден Кайзер', 42366, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (102, 'Зёльден', 5428, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (103, 'Иглс', 7832, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (104, 'Иннсбрук', 5325, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (105, 'Ишгль', 5776, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (106, 'Капрун', 5777, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (107, 'Качберг', 46629, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (108, 'Кирхберг', 5798, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (109, 'Китцбюль', 5778, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (110, 'Ленгенфельд', 5348, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (111, 'Лех', 5353, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (112, 'Майрхофен', 5856, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (113, 'Наудерс', 9498, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (114, 'Нойштифт', 5779, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (115, 'Обергургль', 10432, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (116, 'Пицталь', 31775, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (117, 'Сант - Антон', 5433, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (118, 'Серфаус', 5421, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (119, 'Тироль', 8232, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (120, 'Трополах', 49811, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (121, 'Фульпмес', 31786, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (122, 'Фюген', 12600, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (123, 'Хинтерглемм', 5314, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (124, 'Хинтертукс', 5315, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (125, 'Целль ам Зее', 5468, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (126, 'Шюттдорф', 19434, 12);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (127, 'Баку', 25811, 13);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (128, 'Андорра Ла Велья', 6082, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (129, 'Гранд Валира', 21773, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (130, 'Канильо', 6083, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (131, 'Ла Кортинада', 8226, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (132, 'Массана', 6084, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (133, 'Ордино', 5379, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (134, 'Пал Аринсал', 5381, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (135, 'Пас Де Ла Каса', 6085, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (136, 'Рансол', 11764, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (137, 'Сольдеу', 6086, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (138, 'Фортуна', 41850, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (139, 'Эль Тартер', 6118, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (140, 'Энкамп', 6087, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (141, 'Эскальдес', 6120, 14);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (142, 'Барилоче', 15402, 15);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (143, 'Буэнос Айрес', 11178, 15);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (144, 'Калафате', 11180, 15);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (145, 'Мар Дель Плата', 15368, 15);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (146, 'Мендоза', 18712, 15);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (147, 'Ушуайя', 15366, 15);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (148, 'Алаверди', 43048, 16);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (149, 'Гюмри', 43083, 16);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (150, 'Джермук', 41453, 16);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (151, 'Дилижан', 41454, 16);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (152, 'Ереван', 11182, 16);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (153, 'Лори', 41456, 16);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (154, 'Севан', 33028, 16);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (155, 'Цахкадзор', 41457, 16);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (156, 'Манама', 28177, 17);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (157, 'Антверпен', 13724, 18);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (158, 'Брюгге', 13914, 18);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (159, 'Брюссель', 7870, 18);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (160, 'Банско', 8020, 19);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (161, 'Боровец', 8282, 19);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (162, 'Варна', 5460, 19);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (163, 'Золотые Пески', 5308, 19);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (164, 'Несебр', 13738, 19);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (165, 'Обзор', 13740, 19);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (166, 'Пампорово', 8284, 19);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (167, 'Разлог', 11216, 19);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (168, 'Св. Константин и Елена', 8266, 19);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (169, 'Солнечный Берег', 5436, 19);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (170, 'София', 6458, 19);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (171, 'Ангра-дос-Рейс', 5225, 20);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (172, 'Бузиос', 5247, 20);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (173, 'Игуасу', 5322, 20);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (174, 'Рио-де-Жанейро', 5406, 20);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (175, 'Лондон', 6372, 21);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (176, 'Эдинбург', 7898, 21);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (177, 'Алшоёрш', 43652, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (178, 'Балатон', 8374, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (179, 'Балатонсарсо', 43642, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (180, 'Будапешт', 6246, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (181, 'Бюкфюрде', 8380, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (182, 'Дебрецен', 6276, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (183, 'Залакарош', 13758, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (184, 'Тапольца', 8376, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (185, 'Хайдусобосло', 7896, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (186, 'Харкань', 18388, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (187, 'Хевиз', 6960, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (188, 'Шарвар', 8378, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (189, 'Эгер', 6956, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (190, 'Эгерсалок', 31075, 22);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (191, 'Каракас', 11210, 23);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (192, 'Пуэрто-Ордас', 36002, 23);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (193, 'Вунг Тау', 19660, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (194, 'Дананг', 19600, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (195, 'Ня Чанг', 9488, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (196, 'Нячанг + Сайгон', 20087, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (197, 'о. Фу Куок', 11688, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (198, 'Сайгон', 11354, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (199, 'Фантьет', 9490, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (200, 'Фантьет + Сайгон', 20064, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (201, 'Фукуок + Сайгон', 27071, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (202, 'Халонг', 11682, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (203, 'Ханой', 11680, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (204, 'Хойан', 11702, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (205, 'Хошимин', 8162, 24);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (206, 'Баден Баден', 9952, 25);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (207, 'Гармиш-Партенкирхен', 8356, 25);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (208, 'Дюсельдорф', 7710, 25);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (209, 'Гонконг', 39203, 26);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (210, 'Анаклиа', 28929, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (211, 'Бакуриани', 10354, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (212, 'Батуми', 16668, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (213, 'Боржоми', 28717, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (214, 'Гудаури', 10358, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (215, 'Квариати', 16670, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (216, 'Кобулети', 16672, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (217, 'Кутаиси', 19703, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (218, 'Саирме', 41616, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (219, 'Тбилиси', 11448, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (220, 'Уреки', 18967, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (221, 'Цхалтубо', 36045, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (222, 'Чакви', 28525, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (223, 'Экскурсионные туры - Грузия', 18150, 27);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (224, 'Копенгаген', 7380, 28);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (225, 'Леголенд', 28682, 28);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (226, 'Бока Чика', 5244, 29);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (227, 'Кап Кана', 25549, 29);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (228, 'Ла Романа', 37699, 29);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (229, 'Пунта Кана', 5399, 29);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (230, 'Пуэрто-Плата', 5398, 29);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (231, 'Самана', 5540, 29);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (232, 'Санто-Доминго', 5417, 29);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (233, 'Хуан Долио', 5329, 29);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (234, 'Ашдод', 33145, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (235, 'Ашкелон', 15086, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (236, 'Бат Ям', 6864, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (237, 'Герцлия', 5897, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (238, 'Иерусалим', 5797, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (239, 'Израиль+Иордания', 36175, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (240, 'Кесария', 5900, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (241, 'Мёртвое Море', 5555, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (242, 'Митцпе Рамон', 14722, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (243, 'Нетания', 5894, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (244, 'Нетания+Эйлат', 32795, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (245, 'Реховот', 27581, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (246, 'Тверия', 5556, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (247, 'Тель Авив', 5557, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (248, 'Тель Авив+Мёртвое море', 28874, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (249, 'Тель Авив+Эйлат', 28875, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (250, 'Хайфа', 5898, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (251, 'Эйлат', 5554, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (252, 'Экскурсионные Туры - Израиль', 6334, 30);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (253, 'Аюрведические Пакеты', 20569, 31);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (254, 'Бамболим', 9740, 31);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (255, 'ГОА', 5472, 31);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (256, 'ГОА северный', 8082, 31);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (257, 'ГОА южный', 8080, 31);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (258, 'Дели', 6282, 31);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (259, 'Калангут', 9588, 31);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (260, 'Кандолим', 9582, 31);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (261, 'Керала', 9608, 31);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (262, 'Экскурсионный тур - Индия', 5901, 31);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (263, 'Бали', 5865, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (264, 'Бинтан', 29535, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (265, 'Гили Траванган', 10540, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (266, 'Кандидаса', 12246, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (267, 'Карангасем', 29799, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (268, 'Кута & Легиан', 10446, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (269, 'Ловина', 11814, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (270, 'Ломбок', 19291, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (271, 'Нуса Дуа', 6090, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (272, 'Санур', 8150, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (273, 'Семиняк', 11781, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (274, 'Табанан', 19288, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (275, 'Танджунг Беноа', 6088, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (276, 'Убуд', 7968, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (277, 'Улувату', 8386, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (278, 'Унгасан', 14532, 32);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (279, 'Акаба', 6058, 33);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (280, 'Амман', 6061, 33);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (281, 'Мер.море + Кр.море', 19490, 33);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (282, 'Мертв. море', 9526, 33);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (283, 'Петра', 8780, 33);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (284, 'Абано Терме', 8688, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (285, 'Амальфи', 8580, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (286, 'Бормио', 10018, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (287, 'Вал Рендена', 10020, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (288, 'Валь Гардена', 10016, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (289, 'Валь Д''аоста', 12134, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (290, 'Валь Ди Соле', 38417, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (291, 'Валь ди Фасса', 11300, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (292, 'Венецианская Ривьера', 21723, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (293, 'Венеция', 8762, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (294, 'Гарда', 8724, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (295, 'Диано Марина', 32717, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (296, 'Доломитовые Альпы', 11992, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (297, 'Искья', 8566, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (298, 'Кавалезе', 21010, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (299, 'Капри', 8576, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (300, 'Карано', 38279, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (301, 'Кастелло-Молина-Ди-Фьемме', 38278, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (302, 'Кортина дАмпецо', 10024, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (303, 'Кронплатц', 18544, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (304, 'Ливиньо', 11294, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (305, 'Лигурийская Ривьера', 43414, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (306, 'Лигурия', 21729, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (307, 'Милан', 8754, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (308, 'Неаполитанская Ривьера', 21730, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (309, 'Оз. Комо', 8700, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (310, 'Оз. Маджоре', 21725, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (311, 'Предаццо', 38281, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (312, 'Ривьера ди Леванте', 6974, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (313, 'Ривьера ди Поненте', 6962, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (314, 'Ривьера-Ди-Улиссе', 8582, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (315, 'Рим', 7900, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (316, 'Римини', 8662, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (317, 'Риччоне', 8658, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (318, 'Сардиния', 8446, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (319, 'Сицилия', 7663, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (320, 'Сорренто', 8544, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (321, 'Тоскана', 8770, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (322, 'Флоренция', 8760, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (323, 'Циано Ди Фьемме', 38276, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (324, 'Червиния', 10022, 34);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (325, 'Кампонг Тхом', 24933, 35);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (326, 'Кеп', 32678, 35);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (327, 'Пномпень', 12012, 35);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (328, 'Сиануквиль', 19232, 35);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (329, 'Сием Риеп', 5425, 35);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (330, 'Доха', 28315, 36);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (331, 'Айя Напа', 6700, 37);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (332, 'Ларнака', 6708, 37);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (333, 'Лимассол', 6702, 37);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (334, 'Пафос', 6698, 37);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (335, 'Писсури', 6706, 37);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (336, 'Протарас', 6704, 37);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (337, 'Гуанчжоу', 17042, 38);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (338, 'Пекин', 7360, 38);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (339, 'Санья', 8290, 38);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (340, 'Шанхай', 7362, 38);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (341, 'Экскурсионные Туры - Китай', 9888, 38);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (342, 'Ялонг Бей', 11795, 38);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (343, 'Сан-Хосе', 18508, 39);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (344, 'Варадеро', 5459, 40);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (345, 'Гавана', 5805, 40);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (346, 'Гавана+Варадеро', 11506, 40);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (347, 'Кайо Гильермо', 5257, 40);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (348, 'Кайо Санта Мария', 5260, 40);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (349, 'Кайо-Коко', 5255, 40);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (350, 'Кайо-Ларго', 6582, 40);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (351, 'Ольгин', 5316, 40);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (352, 'Вьентьян', 32679, 41);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (353, 'Луанг Прабанг', 11684, 41);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (354, 'Тад Ло', 42008, 41);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (355, 'Диклу', 41610, 42);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (356, 'Рига', 7312, 42);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (357, 'Сигулда', 29661, 42);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (358, 'Цесис', 31306, 42);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (359, 'Юрмала', 7314, 42);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (360, 'Бейрут', 9642, 43);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (361, 'Вильнюс', 7708, 44);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (362, 'Друскининкай', 13000, 44);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (363, 'Каунас', 6342, 44);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (364, 'Клайпеда', 29755, 44);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (365, 'Паланга', 6420, 44);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (366, 'Швентойи', 41631, 44);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (367, 'Маврикий', 9670, 45);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (368, 'Битола', 43039, 46);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (369, 'Маврово', 43041, 46);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (370, 'Охрид', 12890, 46);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (371, 'Попова Шапка', 43040, 46);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (372, 'Скопье', 6568, 46);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (373, 'Борнео', 8802, 47);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (374, 'Куала Лумпур', 8828, 47);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (375, 'Лангкави', 8826, 47);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (376, 'Пенанг', 8834, 47);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (377, 'Тиоман', 8830, 47);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (378, 'Мале', 6600, 48);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (379, 'Аура', 6846, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (380, 'Буджиба', 6852, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (381, 'Гзира', 15954, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (382, 'Гозо', 6858, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (383, 'Комино', 6856, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (384, 'Марфа', 15952, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (385, 'Мдина', 35787, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (386, 'Меллиха', 6860, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (387, 'Сент Джулианс', 6844, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (388, 'Слима', 6848, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (389, 'Ст. Паулс Бэй', 37517, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (390, 'Флориана', 6850, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (391, 'Чиркевва', 6854, 49);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (392, 'Агадир', 8838, 50);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (393, 'Касабланка', 8840, 50);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (394, 'Марракеш', 8842, 50);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (395, 'Рабат', 24878, 50);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (396, 'Эс-Сувейра', 14972, 50);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (397, 'Канкун', 6636, 51);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (398, 'Косумель', 19621, 51);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (399, 'Мехико', 6656, 51);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (400, 'Ривьера-Майа', 6642, 51);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (401, 'Экскурсионные Туры - Мексика', 7618, 51);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (402, 'Амстердам', 7868, 52);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (403, 'Осло', 6418, 53);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (404, 'Тромсё', 18190, 53);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (405, 'Хитра', 33136, 53);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (406, 'Маскат', 28864, 54);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (407, 'Бялка Татшанска', 19334, 55);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (408, 'Варшава', 9882, 55);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (409, 'Висла', 10012, 55);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (410, 'Вроцлав', 9996, 55);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (411, 'Гданьск', 10004, 55);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (412, 'Закопане', 7946, 55);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (413, 'Карпач', 20920, 55);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (414, 'Колобжег', 50300, 55);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (415, 'Краков', 7890, 55);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (416, 'Крыница', 8910, 55);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (417, 'Алгарве', 8916, 56);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (418, 'Лиссабон', 7792, 56);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (419, 'Лиссабонская Ревьера', 9008, 56);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (420, 'Мадейра', 7802, 56);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (421, 'Порто', 8556, 56);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (422, 'Ла Диг', 10510, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (423, 'Маэ', 9672, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (424, 'о. Бёрд', 20348, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (425, 'о. Денис', 12658, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (426, 'о. Кузин', 14596, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (427, 'о. Норт', 14598, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (428, 'о. Раунд', 14600, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (429, 'о. Святой Анны', 10514, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (430, 'о. Серф', 14604, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (431, 'о. Фрегат', 14594, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (432, 'о.Дерош', 14606, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (433, 'Праслин', 9886, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (434, 'Силуэт', 10512, 57);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (435, 'Белград', 12086, 58);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (436, 'Сентоза', 13836, 59);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (437, 'Сингапур', 5426, 59);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (438, 'Сингапур+Бали', 11508, 59);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (439, 'Бардеевские Купеле', 12094, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (440, 'Бешенева', 20218, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (441, 'Бойнице', 12716, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (442, 'Братислава', 10356, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (443, 'Высокие Татры', 28764, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (444, 'Вышне Ружбахи', 12714, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (445, 'Деменовская долина', 19817, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (446, 'Дудинце', 12142, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (447, 'Ждиар', 20214, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (448, 'Кошице', 32205, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (449, 'Липтовски Микулаш', 10422, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (450, 'Липтовский Ян', 10410, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (451, 'Низкие Татры', 11394, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (452, 'Подбанске', 9026, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (453, 'Попрад', 7894, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (454, 'Пьештяны', 12144, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (455, 'Смоковец', 9020, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (456, 'Смрдаки', 14850, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (457, 'Стара Любовна', 10424, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (458, 'Татранска Ломница', 9018, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (459, 'Татранская Матлиара', 11134, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (460, 'Штребске Плесо', 9022, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (461, 'Ясна', 9034, 60);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (462, 'Блед', 10910, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (463, 'Бохинь', 10908, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (464, 'Доленске Топлице', 20287, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (465, 'Изола', 14814, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (466, 'Краньска Гора', 9038, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (467, 'Любляна', 13846, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (468, 'Марибор', 11322, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (469, 'Моравске Топлице', 20286, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (470, 'Пиран', 14816, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (471, 'Порторож', 13848, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (472, 'Рогашка', 11328, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (473, 'Рогла', 20194, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (474, 'Струньян', 13852, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (475, 'Терме Лашко', 20288, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (476, 'Терме Олимия', 12756, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (477, 'Терме Чатеж', 12760, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (478, 'Термы Лендава', 31946, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (479, 'Термы Птуй', 31801, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (480, 'Термы Раденце', 20285, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (481, 'Шмарьешке Топлице', 13854, 61);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (482, 'Лас Вегас', 9480, 62);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (483, 'Майами', 11162, 62);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (484, 'Нью-Йорк', 9470, 62);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (485, 'Сан-Франциско', 9482, 62);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (486, 'Бангкок', 6044, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (487, 'Бангкок+Ко Чанг+Бангкок', 31932, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (488, 'Као Лак', 5997, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (489, 'Као Лак+Бангкок', 11787, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (490, 'Ко Чанг', 6081, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (491, 'Ко Чанг+Бангкок', 6746, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (492, 'Ко Чанг+Паттайя', 7422, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (493, 'Краби', 5799, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (494, 'Краби+Бангкок', 9756, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (495, 'Краби+Паттайя', 28029, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (496, 'Ланта', 5349, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (497, 'Ланта+Бангкок', 9774, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (498, 'Пай', 42061, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (499, 'Паттайа+Пхукет', 43618, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (500, 'Паттайя', 5418, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (501, 'Паттайя+Бангкок', 7434, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (502, 'Паттайя+Ко Чанг+Бангкок', 7424, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (503, 'Паттайя+Краби+Бангкок', 11474, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (504, 'Паттайя+Пхукет+Бангкок', 7416, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (505, 'Паттайя+Самет+Бангкок', 7436, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (506, 'Паттайя+Самуи+Бангкок', 11476, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (507, 'Пханган', 5333, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (508, 'Пхи Пхи+Пхукет+Бангкок', 12122, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (509, 'Пхи-Пхи', 5390, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (510, 'Пхи-Пхи+Бангкок', 9780, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (511, 'Пхукет', 5341, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (512, 'Пхукет+Бангкок', 7432, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (513, 'Районг', 5402, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (514, 'Районг+Бангкок', 41619, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (515, 'Самет', 5413, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (516, 'Самет+Бангкок', 7440, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (517, 'Самуи', 6066, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (518, 'Самуи+Бангкок', 6750, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (519, 'Самуи+Паттайя', 15282, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (520, 'Хуа Хин', 5318, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (521, 'Хуа Хин+Бангкок', 8156, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (522, 'Хуа Хин+Паттайа', 17744, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (523, 'Хуа Хин+Паттайа+Бангкок', 17742, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (524, 'Чианг Май', 5263, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (525, 'Чианг Рай', 5264, 63);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (526, 'Аруша', 14652, 64);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (527, 'Восточное побережье', 14442, 64);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (528, 'Дар-эс-Салам', 14650, 64);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (529, 'Занзибар', 11338, 64);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (530, 'Северное побережье', 23878, 64);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (531, 'Махдия', 6690, 65);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (532, 'Монастир', 6696, 65);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (533, 'Набель', 7046, 65);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (534, 'Сусс', 6692, 65);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (535, 'Тунис', 7044, 65);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (536, 'Хаммамет', 6694, 65);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (537, 'Алушта', 5221, 66);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (538, 'Ждениево', 10066, 66);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (539, 'Закарпатье', 5880, 66);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (540, 'Ивано-Франковск', 6336, 66);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (541, 'Каменец-Подольский', 15170, 66);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (542, 'Коломия', 38704, 66);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (543, 'Миргород', 5370, 66);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (544, 'Моршин', 5372, 66);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (545, 'Одесса', 6412, 66);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (546, 'Поляница', 10360, 66);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (547, 'Трускавец', 11142, 66);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (548, 'Яремче', 11144, 66);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (549, 'Боракай', 15872, 67);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (550, 'Бохол', 30539, 67);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (551, 'Манила', 15874, 67);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (552, 'Минданао', 41940, 67);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (553, 'Миндоро', 30716, 67);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (554, 'Негрос', 41939, 67);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (555, 'Палаван', 15876, 67);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (556, 'Себу', 12194, 67);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (557, 'Куусамо-Рука', 7882, 68);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (558, 'Леви', 9326, 68);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (559, 'Люосто', 18730, 68);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (560, 'Рованиеми', 9328, 68);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (561, 'Хельсинки', 8198, 68);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (562, 'Авориаз', 18779, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (563, 'Антибы', 7272, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (564, 'Канны', 7268, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (565, 'Корсика', 8326, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (566, 'Марсель', 7804, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (567, 'Межев', 20415, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (568, 'Монако', 7270, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (569, 'Ницца', 6912, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (570, 'Париж', 6954, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (571, 'Сан -Тропе', 11350, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (572, 'Сан-Максим', 16386, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (573, 'Французские Альпы', 11352, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (574, 'Шамони', 12878, 69);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (575, 'Брач', 6830, 70);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (576, 'Брела', 6888, 70);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (577, 'Дубровник', 7054, 70);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (578, 'Ловран', 7776, 70);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (579, 'Омиш', 6834, 70);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (580, 'Подстрана', 14988, 70);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (581, 'Пореч', 18624, 70);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (582, 'Слано', 7060, 70);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (583, 'Трогир', 6882, 70);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (584, 'Тучепи', 6828, 70);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (585, 'Умаг', 6874, 70);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (586, 'Цавтат', 7056, 70);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (587, 'Карловы Вары', 8300, 71);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (588, 'Константиновы Лазне', 28508, 71);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (589, 'Лугачовице', 40653, 71);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (590, 'Марианские Лазнe', 8292, 71);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (591, 'Подебрады', 19088, 71);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (592, 'Прага', 6432, 71);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (593, 'Теплице', 27887, 71);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (594, 'Франтишковы Лазне', 8294, 71);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (595, 'Шпиндлеров Млын', 10544, 71);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (596, 'Экскурсионные Туры - Чехия', 12474, 71);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (597, 'Яхимов', 8296, 71);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (598, 'Бад Цурцах', 20802, 72);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (599, 'Берн', 7866, 72);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (600, 'Гштаад', 20089, 72);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (601, 'Женева', 7846, 72);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (602, 'Ивердон', 20800, 72);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (603, 'Интерлакен', 7856, 72);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (604, 'Лейкербад', 20105, 72);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (605, 'Люцерн', 7854, 72);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (606, 'Саас-Фе', 20097, 72);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (607, 'Санкт Мориц', 7850, 72);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (608, 'Церматт', 7862, 72);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (609, 'Цюрих', 7852, 72);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (610, 'Гетеборг', 18594, 73);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (611, 'Мальмё', 32665, 73);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (612, 'Стокгольм', 7452, 73);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (613, 'Аругам-Бей', 16176, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (614, 'Ахангама', 17054, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (615, 'Ахунгалла', 5217, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (616, 'Балапития', 40384, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (617, 'Бентота', 6096, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (618, 'Берувелла', 6098, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (619, 'Ваддува', 6108, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (620, 'Вайккал', 5463, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (621, 'Велигама', 5464, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (622, 'Галле', 6110, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (623, 'Диквелла', 5288, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (624, 'Индурува', 6112, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (625, 'Калпития', 16372, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (626, 'Калутара', 6102, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (627, 'Коггала', 5337, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (628, 'Коломбо', 5267, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (629, 'Косгода', 5344, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (630, 'Маравила', 5367, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (631, 'Маунт Лавиния', 6104, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (632, 'Мирисса', 10584, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (633, 'Негомбо', 6106, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (634, 'Нилавели', 32148, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (635, 'Панадура', 25709, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (636, 'Пасикуда', 19252, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (637, 'Тангалле', 5440, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (638, 'Тринкомали', 5449, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (639, 'Унаватуна', 5456, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (640, 'Хиккадува', 6100, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (641, 'Экскурсионный тур - Шри Ланка', 6294, 74);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (642, 'Курессааре', 28687, 75);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (643, 'Пярну', 28686, 75);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (644, 'Таллин', 7316, 75);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (645, 'Тарту', 41692, 75);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (646, 'Монтего Бей', 11566, 76);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (647, 'Негрил', 11570, 76);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (648, 'Очо Риос', 11568, 76);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (649, 'Ранавей Бэй', 11928, 76);
INSERT INTO softtour.region (id, name, itTourId, country_id) VALUES (650, 'Токио', 9632, 77);