package com.softserveinc.softtour.parsers;

import com.softserveinc.softtour.bean.BusRoute;
import com.softserveinc.softtour.parsers.constants.ParsersConstants;
import com.softserveinc.softtour.util.BusParserUrlGenerator;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

import java.io.IOException;
import java.text.ParseException;
import java.util.*;

/**
* This class find routes from user's chosen city to tour departure city.
* The routes data source is site: http://ticket.bus.com.ua
* This class use:
*   com.softserveinc.softtour.parsers.constants.ParsersConstants - contains used in this class constants
*   com.softserveinc.softtour.bean.BusRoute - represent bus route
*   com.softserveinc.softtour.util.BusParserUrlGenerator - generate web-page's url, that contains bus routes.
*/
public class BusParser implements ParsersConstants {

    /**
     * Parse results would be save in this list
     */
    private List<BusRoute> busRouteList;
    private String cityFrom;
    private String cityTo;

    /**
    * This variable represents date & time, when user go to tour from departure city
    */
    private Date departureDateTime;
    private Date reducedDateTime;

    /**
    * Creates new BusParser with params:
    * @param cityFrom - user's chosen city
    * @param cityTo - tour departure city
    * @param departureDate - represent date, when user go to tour from departure city, String in format yyyy-MM-dd
    * @param departureTime - represent time, when user go to tour from departure city, String in format HH:mm
    * */
    public BusParser(String cityFrom, String cityTo, String departureDate, String departureTime) {
        this.busRouteList = new ArrayList<>();
        this.cityFrom = cityFrom;
        this.cityTo = cityTo;
        try {
            /**
             * This variable contains departure date & time, converted from String to java.util.Date
             */
            this.departureDateTime = INPUT_DATE_TIME_FORMAT.parse(departureDate + departureTime);
        }catch (ParseException e){
            System.err.print("Unparsable data. Departure date - " + departureDate + " must be in format yyyy-MM-dd " +
                    "Departure time " + departureTime + " must be in format - HH:mm ");
        }
    }

    /**
     * This method create two connections:
     *     First connection find routes on day, that is three hours earlier departureDateTime.
     *         The reason is that client must come to departure point earlier to pass registration.
     *         The registration passes about three hours.
     *     Second connection find routes on day, that is the day earlier then first connection.
     *
     *     Example: Departure date: 2014-11-12, departure time: 02:00.
     *     First connection will find routes on date: 2014-11-11.
     *     Second connection will find routes on date: 2014-11-10.
     *
     *     In this case Strings firstDateUrl and secondDateUrl are the urls with reduced date parameters.
     *     This Strings received by using private method generateUrl.
     *
     *     Web-pages with routes are encapsulated in Jsoup object Document.
     *     Document will be generated by using private method connect.
     *
     *     Private method addRoutes finds in the document BusRoute data and adds bus routes to busRouteList.
     *
     *     Methods connect and addRoutes used twice, because we have two urls for two departure dates.
     *
     *     Private method removeWasteRoutes used to remove routes, that are later, than departureDateTime
     *
     * @return list of bus routes (represented by BusRoute class)
     */
    public List<BusRoute> parse() {
        String firstDateUrl = generateUrl(FIRST_DATE_REDUCE);
        String secondDateUrl = generateUrl(SECOND_DATE_REDUCE);
        Document document = connect(firstDateUrl);
        addRoutes(document);
        document = connect(secondDateUrl);
        addRoutes(document);
        return busRouteList;
    }

    /**
     * @param dateReduce - milliseconds of date reducing
     * @return web-page's url with bus routes
     */
    private String generateUrl(long dateReduce){
        Date reducedDate = new Date(departureDateTime.getTime() - dateReduce);
        if(reducedDateTime == null){
            reducedDateTime = reducedDate;
        }
        String resultDateString = SIMPLE_DATE_FORMAT.format(reducedDate);
        BusParserUrlGenerator generator = new BusParserUrlGenerator();
        String url = generator.createSearchUrl(cityFrom, cityTo, resultDateString);
        return url;
    }

    /**
     * @param url - web-page's url with bus routes
     * @return web-page, encapsulated in Jsoup object Document
     */
    private Document connect(String url){
        String doc = null;
        try {
            doc = Jsoup.connect(url).
                    timeout(CONNECTION_TIMEOUT).
                    ignoreContentType(true).
                    execute().
                    body();
        } catch (IOException e) {
            e.printStackTrace();
        }
        Document document = Jsoup.parse(doc);
        return document;
    }

    /**
     * This method get from document bus routes data, create BusRoute objects and add routes to busRouteList
     * @param document - web-page, encapsulated in Jsoup object Document
     */
    private void addRoutes(Document document){

        /**
         * This list contains rows from all tables in web-page with bus routes.
         * There were no tag-parameters like id, class, etc to find table rows, that we need.
         * The data, that will be use, starts from seven element of the list.
         */
        List<Element> elementList = document.getElementsByTag(TAG_TR);
        for(int i = DATA_START_NUMBER; i < elementList.size(); i++){

            /**
             * Data list contains such data:
             * [index]:[value]
             *    0   : Tags tg, div & 4 span, not used
             *    1   : Bus date departure
             *    2   : Bus station contacts & tag b with departure time
             *    3   : Arrival time & city from (in tag small)
             *    4   : Price
             *    5   : Distance
             *    6   : Percent of route stability
             *    7   : Route code & name
             *    8   : Mark of bus
             *    9   : Img
             *   10   : Empty tag td
             */
            List<Element> dataList = elementList.get(i).getElementsByTag(TAG_TD);

            /**
             * Return from cycle for if elementList contains element with text: '*'
             * The data, contains after this element isn't needed.
             */
            if (dataList.get(0).text().equals("*")){
                return;
            }

            String id = dataList.get(7).text();
            String departureCity = cityFrom;
            String arrivalCity = cityTo;
            String departureDate = dataList.get(1).text();
            String departureTime = dataList.get(2).getElementsByTag(TAG_B).first().text();
            String arrivalTime = dataList.get(3).ownText();
            String price = dataList.get(4).text();

            String departureDateTime = departureDate + departureTime;
            Date routeDepartureDate = null;
            try {
                routeDepartureDate = SIMPLE_DATE_TIME_FORMAT.parse(departureDateTime);
            } catch (ParseException e) {
                e.printStackTrace();
            }

            if(routeDepartureDate.after(reducedDateTime)){
                continue;
            } else {
                String arrivalDateTime = departureDate + arrivalTime;
                Date routeArrivalDate = null;
                try {
                    routeArrivalDate = SIMPLE_DATE_TIME_FORMAT.parse(arrivalDateTime);
                } catch (ParseException e) {
                    e.printStackTrace();
                }
                String onWayTime = calculateOnWayTime(routeDepartureDate, routeArrivalDate);
                BusRoute route = new BusRoute(id, departureCity, arrivalCity, departureDate, departureTime, onWayTime,
                        arrivalTime, price, price);
                busRouteList.add(route);
            }
         }
    }

    private String calculateOnWayTime(Date routeDepartureDate, Date routeArrivalDate){
        if(routeArrivalDate.before(routeDepartureDate)){
            routeArrivalDate.setTime(routeArrivalDate.getTime() + ONE_DAY_IN_MILLISECONDS);
        }
        long timeOnWayInMilliseconds = routeArrivalDate.getTime() - routeDepartureDate.getTime();
        Date onWay = new Date(timeOnWayInMilliseconds);
        Calendar calendar = new GregorianCalendar();
        calendar.setTime(onWay);
        int onWayHours = calendar.get(Calendar.HOUR);
        int onWayMinutes = calendar.get(Calendar.MINUTE);
        StringBuilder onWayTime = new StringBuilder();
        if(onWayHours < 10){
            onWayTime.append(0).append(onWayHours);
        } else {
            onWayTime.append(onWayHours);
        }
        onWayTime.append(":");
        if(onWayMinutes < 10){
            onWayTime.append(0).append(onWayMinutes);
        } else {
            onWayTime.append(onWayMinutes);
        }
        return onWayTime.toString();
    }

    //TODO DEL !!!
    public static void main(String[] args) {
        BusParser busParser = new BusParser("Львів", "Київ", "2014-11-03", "11:30");
        List<BusRoute> list = busParser.parse();
        for(BusRoute route : list){
            System.out.println(route);
        }
    }
}

